### ISSUE TITLE
Missing input files

### ISSUE THREAD

**Issue by GinnyAquarius** [pachterlab/kallisto_paper_analysis#2]
Hi,
When tried to run ./run_all.sh as instruction, I met this issue:
MissingInputException in line 401 of /mnt/hdd2/ginny/kallisto_paper_analysis/seqc/Snakefile:
Missing input files for rule bgi_emsar:
/mnt/hdd2/ginny/kallisto_paper_analysis/index/Homo_sapiens.GRCh38.80_ercc_emsar_100.rsh

Can you help me with this? 
Thank you very much

**Comment by pimentel** [comment]
Hi @GinnyAquarius,

Sorry about that. I just added the file. Please open another issue if there are any other files missing.


Best,

Harold

**Comment by GinnyAquarius** [comment]
Thank you very much!

**Comment by kspham** [comment]
Seems the link is not working?
